config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  # get 'my_anime_list/oauth_callback'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  patch '/dark_mode', to: 'application#dark_mode'

  # get 'oauth_callback', to: 'my_anime_list#oauth_callback'
  get 'authorize', to: 'my_anime_list#authorize'
  get 'animes', to: 'my_anime_list#animes'
  get 'mangas', to: 'my_anime_list#mangas'

  # root 'my_anime_list#index' # Or any other controller action you prefer
  # root 'my_anime_list#index' # Example: Set root to my_anime_list#index
  get 'movies_and_shows', to: 'media#index'

  resources 'users' do
    member do
      get 'favorite_movies'
      get 'friends'
    end

    collection do
    end
  end

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  mount ActionCable.server => '/cable'

  resources 'friendships', only: [] do

    # member do
    #   post 'add_friend'
    #   delete 'remove_friend'
    # end

    collection do
      get 'friends'
    end

  end

  resources :friendships, only: [] do
    member do
      post 'add_friend'
      delete 'remove_friend'
    end
  end

  resources :friend_requests, only: [] do
    member do
      post 'create_friend_request'
      put :accept
      put :reject
      delete 'remove_friend_request'
    end
    collection do
      get 'friend_requests'
    end
  end

  resources 'media', only: [] do
    collection do
      get :movies
      get :tv_shows
    end
    member do
      get :movie
    end
  end

  resources 'movies', only: [] do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
      get 'favorites'
    end

    collection do
    end
  end

  end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_movies
  has_many :movies, through: :user_movies
  has_one_attached :profile_picture
  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy  #if the user accepts the request a is friend to b and b is friend to a, if we dont use this the only b is friend to a(user_id an friend id in table)
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: 'sender_id', dependent: :destroy #user.sent_friend_requests => select * from friend requests where sender_id = user_id, this is the reason why we are using sender_id as foreign key
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: 'receiver_id', dependent: :destroy #user.received_friend_requests, in the query we use where receiver_id = user.id

  has_many :sent_conversations, class_name: 'Conversation', foreign_key: 'sender_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'
  has_many :messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :username, presence: true, uniqueness: true

  after_create -> (user){ user.update(theme: 'dark') }
  after_create :send_welcome_email

  fullname = -> { firstname + " " + lastname }; define_method :fullname, &fullname
  # Yes, exactly! In Ruby, define_method is a method provided by the Module class,
  # which allows you to dynamically define instance methods. When you have a Proc or a lambda (-> { ... }),
  # you can use define_method to convert it into a method that can be called on instances of the class.

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      username = generate_unique_username(data['first_name'], data['last_name'])
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0, 20],
        firstname: data['first_name'],
        lastname: data['last_name'],
        username: username
      )
    end

    user
  end



  def send_friend_request(user)
    sent_friend_requests.create(receiver: user, status: 'pending') unless friends?(user) || pending_friend_request?(user)
  end

  def accept_friend_request(user)
    request = received_friend_requests.find_by(sender: user, status: 'pending')
    if request
      request.update(status: 'accepted')
      friends << user; user.friends << self
    end
  end

  def sent_friend_request_to?(other_user)
    FriendRequest.exists?(sender_id: self.id, receiver_id: other_user.id)
  end

  def received_friend_request_from?(other_user)
    FriendRequest.exists?(sender_id: other_user.id, receiver_id: self.id)
  end

  def remove_friend_request(receiver)
    request = FriendRequest.find_by(sender: self, receiver: receiver, status: 'pending')
    request.destroy if request
  end

  def reject_friend_request(user)
    request = received_friend_requests.find_by(sender: user, status: 'pending')
    request.update(status: 'rejected') if request
  end

  def pending_friend_request?(user)
    sent_friend_requests.exists?(receiver: user, status: 'pending') || received_friend_requests.exists?(sender: user, status: 'pending')
  end

  def add_friend(friend)
    friendships.create(friend_id: friend.id)
  end

  def remove_friend(friend)
    friendship = friendships.find_by(friend_id: friend.id)
    friendship.destroy if friendship
  end

  def friends?(user)
    friends.include?(user) or user.friends.include?(self)
  end

  def profile_thumbnail
    if profile_picture.attached?
      profile_picture.variant(resize_to_fill: [200, 200]).processed
    else
      '/Avatar2.jpeg'
    end
  end

  private

  def send_welcome_email
    WelcomeMailSideKiqWorker.perform_async('welcome_email', self.id)
  end

  def self.generate_unique_username(firstname, lastname)
    base_username = "#{firstname.downcase}_#{lastname.downcase}"
    username = base_username
    counter = 1

    while User.exists?(username: username)
      username = "#{base_username}_#{counter}"
      counter += 1
    end

    username
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    #after redirection it comes back here and goes to from_omniauth where the user will be created if the user is not present
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # def new
  #   super
  # end
  #
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :username, :firstname, :lastname, :profile_picture])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:new]

  # GET /resource/sign_in
  def new
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  rescue
    flash[:alert] = "Invalid email or password"
    redirect_to root_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # def after_sign_in_path_for(resource)
  #   stored_location_for(resource) || root_path
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def tmdb_service
    TmdbService.new
  end
  def index
    @users = User.where.not(id: current_user.id).page(params[:page]).per(10)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: [params[:id]])
  end

  def favorite_movies
    user = User.find_by(id: params[:id])
    favorite_movies = user.movies.pluck(:movie_id)
    @favorite_movies = favorite_movies.map { |movie_id| tmdb_service.fetch_movie(movie_id) }.compact
    @genres = tmdb_service.fetch_genre_id
    @genres_hash = @genres["genres"].map { |genre| [genre["id"], genre["name"]] }.to_h
  end

  def friends
    user = User.find_by(id: params[:id])
    @friends = user.friends.where.not(id: current_user.id).page(params[:page]).per(10) if user
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/favorite_movies.html.erb
<div class="movie-container">

  <% @favorite_movies.each do |movie| %>
    <%= link_to movie_medium_path(movie["id"]), class: "home-page-card-link" do %>

      <div class="movie-card card w-96 bg-base-100 shadow-xl shadow-xl image-full transform  duration-1000 hover:scale-105">
        <% poster_url = "https://image.tmdb.org/t/p/w500#{movie["poster_path"]}" %>
        <% rating = movie["vote_average"]/2 %>
        <% rating = rating.round %>
        <% movie_genre_names = movie["genres"].map{|a| a["name"]}.join(', ') %>
        <%# backdrop_url = "https://image.tmdb.org/t/p/w500#{movie["backdrop_path"]}" %>
        <figure><img src=<%= poster_url %> alt="Shoes" /></figure>
        <div class="card-body">
          <h2 class="card-title"><%= movie["original_title"] %></h2>
          <p><%= movie["overview"] %></p>
          <div class="bottom-card-container">
            <div class="card-actions justify-start">
              <div class="genre" style="font-size: 12px">
                  <%= movie_genre_names %>
              </div>
            </div>
            <div class="card-actions justify-end">
              <div class="rating">
                <% rating.times do %>
                  <input type="radio" name="rating-2" class="mask mask-star-2 bg-orange-400" />
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/friends.html.erb
<div class="overflow-x-hidden table-container">
  <table class="table">
    <!-- head -->
    <thead>
    <tr>
      <th>
        <!--        <label>-->
        <!--          <input type="checkbox" class="checkbox" />-->
        <!--        </label>-->
      </th>
      <th>Username</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <!-- row 1 -->
    <% @friends.each do |user| %>
      <tr>
        <th>
          <!--        <label>-->
          <!--          <input type="checkbox" class="checkbox" />-->
          <!--        </label>-->
        </th>
        <td>
          <div class="flex items-center gap-3">
            <div class="avatar">
              <div class="mask mask-squircle h-12 w-12">
                <%= link_to user_path(user) do%>
                  <% if user.profile_picture.attached? %>
                    <%= image_tag url_for(user.profile_thumbnail), class: "rounded-xl"%>
                  <% else %>
                    <%= image_tag 'Avatar2.jpeg', alt: 'Relax', class: 'your-css-class' %>
                  <%end %>
                <%end %>
              </div>
            </div>
            <div>
              <div class="font-bold"><%= user.username %></div>

            </div>
          </div>
        </td>
        <td>
          <div class="text-sm opacity-50"><%= user.email %></div>
          <br />
          <!--        <span class="badge badge-ghost badge-sm"></span>-->
        </td>
        <td></td>
        <th>

          <% if !current_user.friends?(user) %>
            <%if current_user.sent_friend_request_to?(user)%>
              <button class="btn btn-ghost btn-xs"><%= link_to 'Remove Request', remove_friend_request_friend_request_path(user.id), method: :delete %></button>
            <% elsif current_user.received_friend_request_from?(user)%>
              <button class="btn btn-ghost btn-xs"><%= link_to 'Accept', accept_friend_request_path(user.id), method: :put %></button> | <button class="btn btn-ghost btn-xs"><%= link_to 'Reject', reject_friend_request_path(user.id), method: :put %></button>
            <% else %>
              <button class="btn btn-ghost btn-xs"><%= link_to 'Add Friend', create_friend_request_friend_request_path(user.id), method: :post %></button>
            <% end %>
          <% elsif current_user.friends?(user) %>
            <button class="btn btn-ghost btn-xs"><%= link_to 'Remove', remove_friend_friendship_path(user.id), method: :delete %></button>
          <% end %>
        </th>
      </tr>
    <% end %>
    <!-- row 2 -->

    </tbody>
    <!-- foot -->
    <tfoot>

    </tfoot>
  </table>
  <%= paginate @friends %>
</div>

app/views/users/index.html.erb
<div class="overflow-x-hidden table-container">
  <table class="table">
    <!-- head -->
    <thead>
    <tr>
      <th>
<!--        <label>-->
<!--          <input type="checkbox" class="checkbox" />-->
<!--        </label>-->
      </th>
      <th>Username</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <!-- row 1 -->
  <% @users.each do |user| %>
    <tr>
      <th>
<!--        <label>-->
<!--          <input type="checkbox" class="checkbox" />-->
<!--        </label>-->
      </th>
      <td>
        <div class="flex items-center gap-3">
          <div class="avatar">
            <div class="mask mask-squircle h-12 w-12">
              <%= link_to user_path(user) do%>
              <% if user.profile_picture.attached? %>
              <%= image_tag url_for(user.profile_thumbnail), class: "rounded-xl"%>
                <% else %>
                <%= image_tag 'Avatar2.jpeg', alt: 'Relax', class: 'your-css-class' %>
              <%end %>
              <%end %>
            </div>
          </div>
          <div>
            <div class="font-bold"><%= user.username %></div>

          </div>
        </div>
      </td>
      <td>
        <div class="text-sm opacity-50"><%= user.email %></div>
        <br />
<!--        <span class="badge badge-ghost badge-sm"></span>-->
      </td>
      <td></td>
      <th>

        <% if !current_user.friends?(user) %>
          <%if current_user.sent_friend_request_to?(user)%>
          <button class="btn btn-ghost btn-xs"><%= link_to 'Remove Request', remove_friend_request_friend_request_path(user.id), method: :delete %></button>
        <% elsif current_user.received_friend_request_from?(user)%>
          <button class="btn btn-ghost btn-xs"><%= link_to 'Accept', accept_friend_request_path(user.id), method: :put %></button> | <button class="btn btn-ghost btn-xs"><%= link_to 'Reject', reject_friend_request_path(user.id), method: :put %></button>
        <% else %>
            <button class="btn btn-ghost btn-xs"><%= link_to 'Add Friend', create_friend_request_friend_request_path(user.id), method: :post %></button>
          <% end %>
        <% elsif current_user.friends?(user) %>
          <button class="btn btn-ghost btn-xs"><%= link_to 'Remove', remove_friend_friendship_path(user.id), method: :delete %></button>
      <% end %>
          </th>
    </tr>
  <% end %>
    <!-- row 2 -->

    </tbody>
    <!-- foot -->
    <tfoot>

    </tfoot>
  </table>
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<div class="user-profile-card card bg-base-100 w-96 shadow-xl">
  <figure class="px-10 pt-10">
    <% if @user.profile_picture.attached? %>
      <%= image_tag url_for(@user.profile_thumbnail), class: "rounded-xl"%>
    <% else %>
      <%= image_tag 'Avatar2.jpeg', alt: 'Relax', class: 'your-css-class' %>
    <%end %>
  </figure>
  <div class="card-body items-center text-center">
    <h2 class="card-title"><%= @user.username %></h2>
    <div class="overflow-x-auto">
      <table class="table ">
        <!-- head -->
        <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <!-- row 1 -->
        <tr>
          <th>First Name</th>
          <td><%= @user.firstname %></td>
        </tr>
        <!-- row 2 -->
        <tr>
          <th>Last Name</th>
          <td><%= @user.lastname %></td>
        </tr>
        <!-- row 3 -->
        <tr>
          <th>Email</th>
          <td><%= @user.email %></td>
        </tr>
        </tbody>
      </table>
    </div>

    <div class="user-profile-actions">
      <% if @user == current_user %>
        <div class="card-actions">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
        </div>
        <% end %>
      <div class="card-actions">
        <% if current_user.friends?(@user) %>
        <%= link_to 'Favorites', favorite_movies_user_path(@user), class: 'btn btn-primary' %>
          <%= link_to 'Chat', conversations_path(sender_id: current_user.id, receiver_id: @user.id), method: :post %>
      <% end %>
          </div>
    </div>

  </div>
</div>