config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  # get 'my_anime_list/oauth_callback'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  patch '/dark_mode', to: 'application#dark_mode'

  # get 'oauth_callback', to: 'my_anime_list#oauth_callback'
  get 'authorize', to: 'my_anime_list#authorize'
  get 'animes', to: 'my_anime_list#animes'
  get 'mangas', to: 'my_anime_list#mangas'

  # root 'my_anime_list#index' # Or any other controller action you prefer
  # root 'my_anime_list#index' # Example: Set root to my_anime_list#index
  get 'movies_and_shows', to: 'media#index'

  resources 'users' do
    member do
      get 'favorite_movies'
      get 'friends'
    end

    collection do
    end
  end

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  mount ActionCable.server => '/cable'

  resources 'friendships', only: [] do

    # member do
    #   post 'add_friend'
    #   delete 'remove_friend'
    # end

    collection do
      get 'friends'
    end

  end

  resources :friendships, only: [] do
    member do
      post 'add_friend'
      delete 'remove_friend'
    end
  end

  resources :friend_requests, only: [] do
    member do
      post 'create_friend_request'
      put :accept
      put :reject
      delete 'remove_friend_request'
    end
    collection do
      get 'friend_requests'
    end
  end

  resources 'media', only: [] do
    collection do
      get :movies
      get :tv_shows
    end
    member do
      get :movie
    end
  end

  resources 'movies', only: [] do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
      get 'favorites'
    end

    collection do
    end
  end

  end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :tmdb_service, only: [:index, :movies, :tv_shows]
  before_action :genres, only: [:index, :movies, :tv_shows]

  def tmdb_service
    TmdbService.new
  end

  def genres
    @genres = tmdb_service.fetch_genre_id
    @genres_hash = @genres["genres"].map { |genre| [genre["id"], genre["name"]] }.to_h
  end
  def index
    @trending_movies = tmdb_service.fetch_trending_movies["results"]
    @trending_tv_shows = tmdb_service.fetch_trending_tv_shows["results"]
  end

  def movies
    @trending_movies = tmdb_service.fetch_trending_movies["results"]
  end

  def tv_shows
    @trending_tv_shows = tmdb_service.fetch_trending_tv_shows["results"]
  end

  def movie
    movie_id = params['id'].to_i
    @movie = tmdb_service.fetch_movie(movie_id)
    movie_pictures = tmdb_service.fetch_movie_images(movie_id)
@movie_pictures = movie_pictures["backdrops"]
  end

end

app/views/media/index.html.erb
<% trending_movie = @trending_movies.first %>
<% movie_poster_url = "https://image.tmdb.org/t/p/w500#{trending_movie["poster_path"]}" %>
<% trending_tv = @trending_tv_shows.first %>
<% tv_poster_url = "https://image.tmdb.org/t/p/w500#{trending_tv["poster_path"]}" %>


<div class="movie-tv-wrapper flex space-x-4">
  <%= link_to movies_media_path, class: "home-page-card-link" do %>
    <div class="home-page-card card w-96 bg-base-100 shadow-xl image-full transform  duration-1000 hover:scale-105">
      <figure>
        <img src="<%= movie_poster_url %>" alt="Movies" />
      </figure>
      <div class="card-body">
        <h2 class="card-title">MOVIES</h2>
        <p>Find All About The Trending Movies</p>
        <div class="card-actions justify-end"></div>
      </div>
    </div>
  <% end %>

  <%= link_to tv_shows_media_path, class: "home-page-card-link" do %>
    <div class="home-page-card card w-96 bg-base-100 shadow-xl image-full transform  duration-1000 hover:scale-105">
      <figure>
        <img src="<%= tv_poster_url %>" alt="TV Shows" />
      </figure>
      <div class="card-body">
        <h2 class="card-title">TV SHOWS</h2>
        <p>Find The Shows To Share With Your Friends And Family</p>
        <div class="card-actions justify-end"></div>
      </div>
    </div>
  <% end %>
</div>

app/views/media/movie.html.erb
<div class="single-movie-container">
  <div class="screen carousel w-full shadow-xl" id="movie-page-w-full" style="border-radius: 20px;">
    <% @movie_pictures.each do |image| %>
      <div id="item1" class="carousel-item w-full">
        <% poster_url = "https://image.tmdb.org/t/p/w500#{image["file_path"]}" %>
        <div class="movie-page-hero carousel-container hero min-h-screen" id="hero-movie-page" style="background-image: url(<%= poster_url %>);">
          <div class="hero-overlay bg-opacity-40"></div>
        </div>
      </div>
    <% end %>
    <div class="badge badge-primary badge-lg" id="tv-on-light"></div>
  </div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <div class="divider">
        <h1 class="mb-5 text-5xl font-bold"><%= @movie["original_title"] %></h1>
      </div>
      <div class="stats shadow">
        <div class="stat place-items-center">
          <div class="stat-title">Downloads</div>
          <div class="stat-value">31K</div>
        </div>

        <div class="stat place-items-center">
          <div class="stat-title">Users</div>
          <div class="stat-value text-secondary">4,200</div>
          <div class="stat-desc text-secondary">↗︎ 40 (2%)</div>
        </div>

        <div class="stat place-items-center">
          <div class="stat-title">New Registers</div>
          <div class="stat-value">1,200</div>
          <div class="stat-desc">↘︎ 90 (14%)</div>
        </div>
      </div>
      <div class="divider"></div>

      <p class="mb-5"><%= @movie["overview"] %></p>
      <div class="divider"></div>

      <div id="favorite_link">
        <% if current_user.movies.pluck(:movie_id).include?(@movie["id"].to_s) %>
          <%= link_to "Remove Favourite", remove_favorite_movie_path(@movie), method: :delete, remote: true, class: "start btn btn-primary" %>
        <% else %>
          <%= link_to "Add Favourite", add_favorite_movie_path(@movie), method: :post, remote: true, class: "start btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
    // in the newer versions of rails, the pages are loaded using turbo-links
    // a library used by Rails to speed up navigation by fetching only the HTML and response(got from request to root_path) needed to render the page,
    // and merging it into the current page without doing a full reload

    // this can sometimes interfere with JavaScript that runs on page load or ducument.loaded (JS is not a html required to render the page)

    // initial when I used document loaded, the carousel was not getting loaded because turbo links was
    //loading the page with only the response from the request,to avoid this we use  turbolinks:load instead of DOMContentLoaded
    document.addEventListener('turbolinks:load', function() {
        const items = document.querySelectorAll('.carousel-item');
        let currentItem = 0;
        const itemCount = items.length;

        function showNextItem() {
            items[currentItem].classList.remove('active');
            currentItem = (currentItem + 1) % itemCount;
            items[currentItem].classList.add('active');
        }

        // Remove 'active' class from all items initially
        items.forEach(item => item.classList.remove('active'));

        // Add 'active' class to the first item
        if (items.length > 0) {
            items[currentItem].classList.add('active');
        }

        setInterval(showNextItem, 10000);


    });

    document.addEventListener('turbolinks:load', function() {
        const startLinks = document.querySelectorAll('.start');
        const screenElement = document.querySelector('.screen');
        const tvLight = document.querySelector('#tv-on-light');

        startLinks.forEach(startLink => {
            startLink.addEventListener('mouseover', function() {
                screenElement.classList.add('hovered');
                tvLight.classList.add('hovered');
            });

            startLink.addEventListener('mouseout', function() {
                screenElement.classList.remove('hovered');
                tvLight.classList.remove('hovered');
            });
        });
    });
</script>

app/views/media/movies.html.erb
<div class="movie-container">

<% @trending_movies.each do |movie| %>
    <%= link_to movie_medium_path(movie["id"]), class: "home-page-card-link" do %>

    <div class="movie-card card w-96 bg-base-100 shadow-xl shadow-xl image-full transform  duration-1000 hover:scale-105">
    <% poster_url = "https://image.tmdb.org/t/p/w500#{movie["poster_path"]}" %>
      <% rating = movie["vote_average"]/2 %>
      <% rating = rating.round %>
      <% movie_genre_names = movie["genre_ids"].map { |id| @genres_hash[id] } %>
    <%# backdrop_url = "https://image.tmdb.org/t/p/w500#{movie["backdrop_path"]}" %>
      <figure><img src=<%= poster_url %> alt="Shoes" /></figure>
      <div class="card-body">
        <h2 class="card-title"><%= movie["original_title"] %></h2>
        <p><%= movie["overview"] %></p>
        <div class="bottom-card-container">
        <div class="card-actions justify-start">
          <div class="genre" style="font-size: 12px">
            <% movie_genre_names.each do |genre| %>
                <%= genre %>
              <% end %>
          </div>
        </div>
        <div class="card-actions justify-end">
          <div class="rating">
            <% rating.times do %>
            <input type="radio" name="rating-2" class="mask mask-star-2 bg-orange-400" />
          <% end %>
              </div>
        </div>
        </div>
      </div>
    </div>
    <% end %>
<% end %>
</div>

app/views/media/tv_shows.html.erb
<div class="movie-container">

  <% @trending_tv_shows.each do |movie| %>
    <%= link_to '#', class: "home-page-card-link" do %>

      <div class="movie-card card w-96 bg-base-100 shadow-xl shadow-xl image-full transform  duration-1000 hover:scale-105">
        <% poster_url = "https://image.tmdb.org/t/p/w500#{movie["poster_path"]}" %>
        <% backdrop_url = "https://image.tmdb.org/t/p/w500#{movie["backdrop_path"]}" %>
        <figure><img src=<%= poster_url %> alt="Shoes" /></figure>
        <div class="card-body">
          <h2 class="card-title"><%= movie["original_title"] %></h2>
          <p><%= movie["overview"] %></p>
          <div class="card-actions justify-end">
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>