config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  # get 'my_anime_list/oauth_callback'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  patch '/dark_mode', to: 'application#dark_mode'

  # get 'oauth_callback', to: 'my_anime_list#oauth_callback'
  get 'authorize', to: 'my_anime_list#authorize'
  get 'animes', to: 'my_anime_list#animes'
  get 'mangas', to: 'my_anime_list#mangas'

  # root 'my_anime_list#index' # Or any other controller action you prefer
  # root 'my_anime_list#index' # Example: Set root to my_anime_list#index
  get 'movies_and_shows', to: 'media#index'

  resources 'users' do
    member do
      get 'favorite_movies'
      get 'friends'
    end

    collection do
    end
  end

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  mount ActionCable.server => '/cable'

  resources 'friendships', only: [] do

    # member do
    #   post 'add_friend'
    #   delete 'remove_friend'
    # end

    collection do
      get 'friends'
    end

  end

  resources :friendships, only: [] do
    member do
      post 'add_friend'
      delete 'remove_friend'
    end
  end

  resources :friend_requests, only: [] do
    member do
      post 'create_friend_request'
      put :accept
      put :reject
      delete 'remove_friend_request'
    end
    collection do
      get 'friend_requests'
    end
  end

  resources 'media', only: [] do
    collection do
      get :movies
      get :tv_shows
    end
    member do
      get :movie
    end
  end

  resources 'movies', only: [] do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
      get 'favorites'
    end

    collection do
    end
  end

  end

app/views/layouts/_navbar.html.erb
<div class="navbar bg-base-100 shadow-xl">
  <div class="navbar-start">
    <div class="dropdown">
      <div class="drawer">
        <input id="my-drawer" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content">
          <!-- Page content here -->
          <label for="my-drawer" class="btn drawer-button" style="background: bottom; border: none;">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
          </label>
        </div>
        <div class="drawer-side" style="z-index: 500">
          <label for="my-drawer" aria-label="close sidebar" class="drawer-overlay"></label>
          <ul class="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
            <!-- Sidebar content here -->
            <% if user_signed_in? %>
              <li><%= link_to movies_and_shows_path do%>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
                <% end %>
                  </li>
              <li><%= link_to 'Favorites', favorite_movies_user_path(current_user) %></li>
              <li><%= link_to 'Friends', friends_user_path(current_user) %></li>
              <li><%= link_to 'Chats', conversations_path %></li>
              <li><%= link_to 'All Users', users_path %>
                <%= link_to 'Profile', user_path(current_user) %>
              <li><%= link_to "My Requests", friend_requests_friend_requests_path  %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure"} %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Home Page", root_path %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar-center">
    <a class="btn btn-ghost text-xl" id="logo-container"><figure >
      <%= image_tag 'site_logo.png', alt: 'Relax', class: 'your-css-class', id: 'site-log' %>
    </figure></a>
  </div>
  <div class="navbar-end">
    <% if user_signed_in? %>
      <%= form_with url: dark_mode_path, method: :patch, local: true, id: 'theme-form' do %>
        <div class="form-group">
          <label class="swap swap-rotate" >
            <input type="checkbox" name="theme" id="dark-mode-checkbox" value="dark" style="display: none;" <%= current_user.theme == 'dark' ? 'checked' : '' %> onchange="this.form.submit()" />
            <svg class="swap-off fill-current w-10 h-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
            <svg class="swap-on fill-current w-10 h-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
          </label>
        </div>
      <% end %>
      <% end %>
    <button class="btn btn-ghost btn-circle">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
    </button>
    <button class="btn btn-ghost btn-circle">
      <div class="indicator">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
        <span class="badge badge-xs badge-primary indicator-item"></span>
      </div>
    </button>
  </div>
</div>
<% if notice.present? or alert.present? %>
  <div role="alert" class="alert alert-dismissible" style="z-index: 200;">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-info shrink-0 w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
    </svg>
    <span><%= notice %></span>
    <span><%= alert %></span>
    <div>
      <button class="btn btn-sm close-alert">close</button>
    </div>
  </div>
<% end %>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const closeButton = document.querySelector('.close-alert');
        const alertDiv = document.querySelector('.alert-dismissible');

        if (closeButton && alertDiv) {
            closeButton.addEventListener('click', function() {
                alertDiv.classList.add('slide-up');

                // Remove the alert from the DOM after the animation completes
                alertDiv.addEventListener('animationend', function() {
                    alertDiv.remove();
                });
            });
        }
    });
    $(document).on('change', '#dark-mode-checkbox', function() {
        var enableDark = $(this).is(':checked');
        console.log('darkmode:', enableDark )
        $.ajax({
            url: '/dark_mode', // Replace with your route to the controller action
            method: 'POST', // Use POST method to send data
            data: { dark_mode: enableDark },
            success: function(response) {
                console.log('Dark mode set successfully');
            },
            error: function(xhr, status, error) {
                console.error('Error setting dark mode:', error);
            }
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% theme = current_user ? current_user.theme : 'dark' %>
<html data-theme=<%=theme%>>
  <head>
    <title>FinanceTracker</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'layouts/navbar' %>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

  </body>
</html>

<script>

</script>